spring:
  application:
    name: supplychainx

  datasource:
    # when app runs inside docker-compose, it must use the service hostname 'mysql'
    url: jdbc:mysql://mysql:3306/supplychainx?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: scx
    password: scxpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

   
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/SupplyChainX
          jwk-set-uri: http://keycloak:8080/realms/SupplyChainX/protocol/openid-connect/certs

  logging:
    level:
      org:
        springframework:
          security: DEBUG

  jwt:
    auth:
      converter:
        resource-id: supplychainx-backend
        principle-attribute: preferred_username